### ISSUE TITLE
Refactor JavaScript code

### ISSUE THREAD

**Issue by carlottahillger** [DIT113-V22/group-06#44]
As a developer I want the code to be easy to understand and read so that I can make necessary changes.

**Acceptance criteria**

- [ ] The javascript code should be stored in two different files one for the drag and drop and one for the mqtt connection and the messages
- [ ] The code should include comments explaining what a method does

**Comment by carlottahillger** [comment]
Are we still gonna do this?

**Comment by gusreinaos** [comment]
No es necesario ahora resolver esta issue.
